logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: cf-demo-oauth2-login
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: oauth2login-demo
            client-secret: secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email, logs.create, logs.read
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: sso
        provider:
          sso:
            issuer-uri: http://localhost:8090/uaa/oauth/token
            user-name-attribute: sub
            #jwk-set-uri: http://localhost:8090/uaa/token_keys